version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      - echo "Library Redy!"
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      - echo "Build Completed!"
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://github-build-code-zip/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name test-cicd-pipeline --s3-bucket github-build-code-zip --s3-key deployment_package.zip
      - echo "Deployment complete!"